# Generated by Django 2.1.5 on 2019-02-28 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0003_auto_20190227_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='userleavinmessage',
            name='message',
            field=models.TextField(default='无', help_text='留言内容'),
        ),
        migrations.AlterField(
            model_name='userleavinmessage',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='上传时间', verbose_name='添加时间'),
        ),
        migrations.AlterField(
            model_name='userleavinmessage',
            name='subject',
            field=models.CharField(default='', help_text='主题', max_length=100, verbose_name='主题'),
        ),
    ]
