# Generated by Django 2.1.5 on 2019-02-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_operation', '0004_auto_20190228_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userleavinmessage',
            name='file',
            field=models.FileField(help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件'),
        ),
    ]
