# Generated by Django 2.1.5 on 2019-02-28 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0012_auto_20190227_1539'),
        ('trade', '0003_auto_20190228_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='order_sn',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='订单号'),
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'goods')},
        ),
    ]
