# Generated by Django 2.1.5 on 2019-01-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20190124_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=models.CharField(max_length=800, verbose_name='商品详细描述'),
        ),
    ]
