# Generated by Django 2.1.5 on 2019-01-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20190124_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_desc',
            field=models.CharField(max_length=800, null=True, verbose_name='商品详细描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='goos_brief',
            field=models.TextField(max_length=300, null=True, verbose_name='商品简短描述'),
        ),
    ]
