# Generated by Django 2.1.5 on 2019-01-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20190124_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goos_front_image',
            field=models.ImageField(blank=True, null=True, upload_to='media/goods/images/', verbose_name='封面图片'),
        ),
    ]
