# Generated by Django 2.1.5 on 2019-01-24 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_auto_20190124_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_front_image_url',
        ),
    ]
