# Generated by Django 2.1.5 on 2019-01-25 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_auto_20190124_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='goods_desc',
        ),
    ]
